### ISSUE TITLE
Sometimes the left offsets of the whole components is wrong

### ISSUE THREAD

**Issue by subwaystation** [graph-genome/Schematize#27]
When browsing through the _arabidopsis thaliana_ data, there is no offset on the left for some cases.
![Screenshot from 2020-03-11 16-26-48](https://user-images.githubusercontent.com/10184961/76507671-7cf65800-644d-11ea-8842-7a6346eb05af.png)
My first wild guess is that this happens when we display data across files. But we have to investigate.

**Comment by josiahseaman** [comment]
I suspect this is not actually a bug.  The bug is that we're not filling the whole screen to the right with additional content.  That's due to having a user controlled endBin, which will be removed #22.

The reason the leftOffset looks weird is because you either render a component or you don't in the viewport.  If your beginBin starts halfway through a component, the whole thing will be rendered and shifted to the left.  If you want white border in the webpage chrome, that needs to encompass the whole App.js.  It's not the fault of the Component Konvas that it is filling all the available space.  Ideally, the full Konva canvas is populated and whitespace is handled with css cropping.
