### ISSUE TITLE
Need for smarter chunk filename finding: CORS or SyntaxError: JSON.parse or FileNotFound

### ISSUE THREAD

**Issue by subwaystation** [graph-genome/Schematize#38]
A fresh master clone fails with
```
`SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`
```
For the full error go to http://193.196.29.55:3000/.

**Comment by subwaystation** [comment]
I restored branch i29 in #32. Cloning this branch, it actually works... so something got messed up in master before this PR.

**Comment by jacobwindsor** [comment]
Related to #29. I think this issue can be closed as duplicate

**Comment by subwaystation** [comment]
Now it works :)

**Comment by josiahseaman** [comment]
The CORS error and other data errors are all related to a mismatch in the data file naming (which is really counterintuitive.  In this line:
https://github.com/graph-genome/Schematize/blob/82d8fe366009d1e2bf51de6c6aa0b1de5fc16dba/src/ViewportInputsStore.js#L23
File names are hard coded.  A regeneration of the data can sometimes push B1phi1 dataset into the double digits: chunk01 vs chunk1.  That's the core problem.  I'm going to reopen this issue until we're no longer vulnerable to this filename hardcoding.

**Comment by josiahseaman** [comment]
This issue has reared its head before in #31, so it's definitely worth solving permanently.  It'll require some thought about triggering tryJSONpath() immediately on load or creating a fallback of some kind.  I do find it useful to cache the filenames for ongoing state, but clearly startup is a problem.

**Comment by subwaystation** [comment]
The error also occurs, when you just navigate the B1phi1 data from left to right. Navigating to the last bin results in 
![image](https://user-images.githubusercontent.com/10184961/77896338-66873380-7278-11ea-8c6a-c063447b4590.png)
, too.

**Comment by josiahseaman** [comment]
@jacobwindsor Will you be resuming work on this Monday?

**Comment by josiahseaman** [comment]
### More detail:
In ViewInputStore we should have a single global state variable for the file open: 
`jsonName: 'run1.B1phi1.i1.seqwish.w100',`  this should then in turn populate two new temporary variables:
```
        startChunkURL: 'test_data/run1.B1phi1.i1.seqwish.w100/chunk0_bin100.schematic.json',
        endChunkURL: 'test_data/run1.B1phi1.i1.seqwish.w100/chunk1_bin100.schematic.json',
```
Currently, our hack is that both of these filenames are sitting in the source code and you need to change all three filenames if you want to change the default.  All of the errors mention above were triggered when some change in our startup broke this fragile hack.  

A much better course of action would be to allow both of these state variable to be blank and still allow a render with a crash.  This will require App.js to have a sufficiently early check that will gracefully back off from render() on an empty `startChunkURL`.  `tryJSONPath()` should then go check bin2file.json, open it and grab the corresponding filenames from inside bin2file.json:
```json
 "files": [
        {
            "file": "chunk0_bin100.schematic.json",
            "first_bin": 0,
            "last_bin": 39
        },
        {
            "file": "chunk1_bin100.schematic.json",
            "first_bin": 40,
            "last_bin": 53
        },
```

This change will seriously help to improve the robustness of our system and save precious developer time on this common and confusing error message.  Asynchronous file fetch is much better than our current synchronous hack in `blockingJsonFetch()`.

**For extra credit:** We may eventually want to read in more than two chunks at a time.  If mobx could take a list of chunk filenames, that would allow us more spanning.  However I avoided coding this at first because it get complicated and mobx.arrays are a pain.  I recommend making the current startChunkURL and endChunkURL more robust first before attempting to replace them entirely.  That can be a separate issue following on #22.

**Comment by jacobwindsor** [comment]
Ill resume work on this tomorrow. I think the issue is trifold: 1) need a good convention to name the chunks and 2) need proper state management of data in React 3) should be using modern fetch API and not xhr (especially not sync xhr). As you highlighted @josiahseaman, the third is particularly important.

Is there a naming convention for the chunks?

**Comment by josiahseaman** [comment]
That's a pretty good summary.  Skip 1) since those are listed in bin2file.json and named inside of component_segmentation, so that's outside current jurisdiction.
